### ISSUE TITLE
Error with language determination?'ModuleNotFoundError: 'box-ui-elements-locale-data'

### ISSUE THREAD

**Issue by JamesBlandford** [box/box-ui-elements#2434]
Hi I have run `yarn install` (and the relevant upgrade commands too, to be sure) but i had an issue running:

```
yarn build:prod:dist 
```

where it says 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/Users/james/Documents/Projects/box-ui-elements/scripts/webpack.config.js:30:25)
```

However, I managed to work out why it was failing there, `LANGUAGE` environment variable wasn't set.

So I tried running

```
LANGUAGE=eng yarn build:prod:dist  
```

Now it complains it cant find the module 

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'box-ui-elements-locale-data' in '/Users/james/Documents/Projects/box-ui-elements/src/elements/common'
```

It worked before (on the previous Box v12 beta) so why has it now failed? I just need to change an option from true to false (the "overwrite" parametert) but it now just fails to compile and I cannot include "dist" in my project

**Comment by JamesBlandford** [comment]
turns out the `LANGUAGE` environment variable should be `en-US` not just `eng`... still, i was expecting `yarn build:prod:dist` to run without any prefix of environment variables. 

possible to set `en-US` as the default?
