### ISSUE TITLE
Getting webpack error due to terser unexpected token: punc (:)

### ISSUE THREAD

**Issue by BustosAndrew** [box/box-ui-elements#2497]
**Environment:**

- Elements version: 12.0.0

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 11.1

**Steps to reproduce the problem:**
1. Have axios installed as an npm package
2. Attempt to install box-ui-elements using npm

**What is the expected behavior? (Screenshots can be helpful here)**
To be able to install the npm package without dependency issues.
**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Npm can't resolve dependency with axios versions. Log:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: integration@0.0.1
npm ERR! Found: axios@0.21.1
npm ERR! node_modules/axios
npm ERR!   axios@"^0.21.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.18.1" from box-ui-elements@12.0.0
npm ERR! node_modules/box-ui-elements
npm ERR!   box-ui-elements@"^12.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bustosman/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bustosman/.npm/_logs/2021-03-23T23_36_28_407Z-debug.log
```
**Link to application or sample code:**
N/A

**Expected behavior**
To be able to install the package without dependency conflicts.

**Additional context**
If I force the install of the package, and then run gulp build, this is the webpack error log I get:
```
[00:13:30] [Webpack errors]:
[00:13:30] activity-sidebar.js from Terser
Unexpected token: punc (:) [webpack://./node_modules/box-ui-elements/node_modules/setimmediate/setImmediate.js:80,12][activity-sidebar.js:30380,18]
    at js_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1288:9)
    at semicolon (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1326:56)
    at simple_statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1583:73)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1369:47)
    at _embed_tokens_wrapper (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1339:26)
    at block_ (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:2172:20)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1403:29)[00:13:30]
```
Please update the package with the newest version of axios. (.21.1) I need to continue with integrating the content explorer into a Microsoft Teams tab. I'm aware box already has an app for this in MS Teams, but it's still limited in search features from what it seems.

**Comment by alexkrolick** [comment]
We are indeed strictly locked onto that version of Axios at the moment. Can you try package aliasing if you need a different version in your app?

https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm#56495651

**Comment by BustosAndrew** [comment]
After downgrading axios, and then installing all the peer dependencies manually, running gulp build still produces the webpack error. Any idea on how to fix that? I can't find the file activity-sidebar.js.

**Comment by BustosAndrew** [comment]
After adding content-preview and content-sidebar to webpack for code splitting this is my new error log:
```
[21:16:03] [Webpack errors]:
[21:16:03] activity-sidebar.js from Terser
Unexpected token: punc (:) [webpack://./node_modules/setimmediate/setImmediate.js:80,12][activity-sidebar.js:31047,18]
    at js_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1288:9)
    at semicolon (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1326:56)
    at simple_statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1583:73)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1369:47)
    at _embed_tokens_wrapper (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1339:26)
    at block_ (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:2172:20)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1403:29)
[21:16:03] 'webpack:client' errored after 46 s
[21:16:03] Error in plugin "webpack"
Message:
    1 webpack error(s) found.
[21:16:03] 'webpack' errored after 46 s
[21:16:03] 'build' errored after 46 s
bustosman@Andrews-MacBook-Air Integration % gulp build
[21:36:55] Using gulpfile ~/Documents/GitHub/Box/Integration/gulpfile.js
[21:36:55] Starting 'build'...
[21:36:55] Starting 'webpack'...
[21:36:55] Starting 'webpack:client'...
[21:36:55] Starting 'webpack:server'...
[21:37:08] Finished 'webpack:server' after 12 s
[21:37:53] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[21:37:53] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[21:37:53] export 'default' (imported as 'tabbable') was not found in 'tabbable' (possible exports: focusable, isFocusable, isTabbable, tabbable)
[21:37:53] [Webpack errors]:
[21:37:53] 67.js from Terser
Unexpected token: punc (:) [webpack://./node_modules/setimmediate/setImmediate.js:80,12][67.js:30817,18]
    at js_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1288:9)
    at semicolon (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1326:56)
    at simple_statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1583:73)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1369:47)
    at _embed_tokens_wrapper (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1339:26)
    at block_ (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:2172:20)
    at statement (/Users/bustosman/Documents/GitHub/Box/Integration/node_modules/terser/dist/bundle.min.js:1403:29)
```

**Comment by alexkrolick** [comment]
Looks like you are bundling UI Elements stand-alone from source. Can you try using the UMD builds from the `dist` folder that ship with the package instead?
- https://developer.box.com/guides/embed/ui-elements/installation/
- https://unpkg.com/browse/box-ui-elements@12.0.0/dist/

**Comment by BustosAndrew** [comment]
How would I modify my current webpack config for the UMD builds?

**Comment by alexkrolick** [comment]
You don't need to webpack the `dist/` files, they are prebuilt and ready for use in a `<script>` tag. You can also use the CDN approach described here: https://developer.box.com/guides/embed/ui-elements/installation/
